name: "Terraform Destroy"
on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: destroy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1"

    defaults:
      run:
        working-directory: Deploy-resources

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -var db_pass=${{ secrets.DB_PASS }} -var db_user=${{ secrets.DB_USER }} -auto-approve
