name: "Terraform Deploy to AWS"
on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "Terrarush-Testing"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "Terraform-IaC-AWS"

jobs:
  terraform:
    name: "Terraform-I"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Deploy-resources

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -var db_pass=${{ secrets.DB_PASS }} -var db_user=${{ secrets.DB_USER }} -auto-approve
        working-directory: Deploy-resources

      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform destroy -auto-approve
        working-directory: Deploy-resources
