name: "Terraform Deploy to AWS"
on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "Terrarush-Testing"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "Terraform-IaC-AWS"
  CONFIG_DIRECTORY: "Deploy-resource"

jobs:
  terraform:
    name: "Terraform-Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    defaults:
      run:
        working-directory: Deploy-resources

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Terraform Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        # run: terraform apply -var db_pass=${{ secrets.DB_PASS }} -var db_user=${{ secrets.DB_USER }} -auto-approve
